import type { DiscProfileSheet, DiscProfile } from "./types";

/**
 * Les 4 profils DISC adaptés au commerçant du Bassin de Thau.
 * On ne met personne dans une case : on repère une tendance dominante
 * pour parler le langage de la personne et ne pas lui faire perdre son temps.
 */
export const profiles: DiscProfileSheet[] = [
  {
    id: "fonceur",
    name: "Le Fonceur",
    tagline: "Direct, pressé, il veut du résultat. Allez droit au but ou il vous coupe.",
    color: "#C2410C",
    recognize: {
      vocabulary: [
        "« Bon, c’est quoi exactement ? »",
        "« Allez-y, je vous écoute, j’ai deux minutes. »",
        "« Ça me rapporte quoi, concrètement ? »",
        "« Venez-en au fait. »",
        "« C’est combien ? »",
        "« Ok, et on fait comment ? »",
        "« Moi, ce qui m’intéresse, c’est le chiffre. »",
      ],
      pace: "Rapide. Il parle vite, finit vos phrases, répond avant la fin de la question. Il enchaîne les sujets et décide en quelques minutes, dans un sens comme dans l’autre.",
      posture: "Debout, bien planté, regard direct. Il continue parfois à faire autre chose en vous écoutant. Poignée de main ferme et courte. S’il s’impatiente, il regarde sa montre ou la porte.",
      questions: [
        "« Ça coûte combien ? »",
        "« En combien de temps c’est en ligne ? »",
        "« Qu’est-ce que ça va me rapporter ? »",
        "« Vous pouvez commencer quand ? »",
        "« Pourquoi vous et pas un autre ? »",
      ],
      environment: "Commerce qui tourne vite : comptoir efficace, file d’attente gérée, affichage simple et gros (prix, promo du jour). Il gère souvent plusieurs choses à la fois, parfois plusieurs affaires. Peu de décoration « pour faire joli », tout est fonctionnel.",
      phone: "Décroche en disant juste « Oui ? » ou le nom du commerce, sèchement. Ton pressé, il demande tout de suite « c’est pour quoi ? ». Il raccroche s’il sent un texte récité. Il peut aussi dire oui au rendez-vous très vite si l’accroche parle de résultat.",
    },
    wants: [
      "Qu’on aille droit au but : le problème, la solution, le résultat, en moins d’une minute.",
      "Des résultats visibles : plus d’appels, plus de réservations, plus de passage.",
      "Garder le contrôle : c’est lui qui décide, pas vous.",
      "Des délais courts et tenus.",
      "Qu’on lui fasse gagner du temps, pas qu’on lui en prenne.",
      "Un interlocuteur sûr de lui, qui répond sans détour.",
    ],
    avoid: [
      "Les longues introductions sur l’agence et votre parcours.",
      "Les détails techniques qu’il n’a pas demandés.",
      "Hésiter ou répondre « ça dépend » sans enchaîner sur une réponse.",
      "Lui dire ce qu’il doit faire sur un ton de donneur de leçons.",
      "Revenir trois fois sur le même argument.",
      "Le relancer tous les deux jours : il le vit comme du harcèlement.",
    ],
    close: "Proposez une décision simple entre deux options claires : « On part sur la fiche Google et la carte NFC, ou vous voulez directement le site ? ». Donnez un délai précis et le premier pas concret. S’il dit oui, arrêtez de vendre et passez à l’organisation.",
    phrases: [
      "Je vais faire court : en 20 minutes je vous montre ce qui vous fait perdre des clients sur Google, et comment on le corrige.",
      "Concrètement, on vous donne une date de mise en ligne dès le départ, et on la tient.",
      "Deux options : on commence petit avec la fiche Google, ou on fait tout d’un coup. Vous choisissez.",
      "Je ne vous fais pas de discours, je vous montre sur votre téléphone.",
      "Mardi 15 h ou jeudi 10 h 30, qu’est-ce qui vous arrange ?",
      "Vous décidez après l’audit. Si ça ne vous parle pas, on en reste là.",
    ],
  },
  {
    id: "analytique",
    name: "L’Analytique",
    tagline: "Chiffres, preuves, détails. Il se méfie du flou et décide lentement, mais solidement.",
    color: "#0071E3",
    recognize: {
      vocabulary: [
        "« Vous avez des chiffres ? »",
        "« Ça marche comment, techniquement ? »",
        "« Qu’est-ce qui est compris exactement ? »",
        "« Je voudrais voir un exemple concret. »",
        "« Il y a un contrat ? Quelle durée ? »",
        "« Je vais comparer. »",
        "« Envoyez-moi un devis détaillé. »",
      ],
      pace: "Lent et posé. Il réfléchit avant de répondre, laisse des silences, revient sur un point précis. Il ne décide presque jamais le jour même.",
      posture: "Réservé, peu expressif, bras parfois croisés par habitude plutôt que par hostilité. Il regarde ce que vous montrez avec attention, peut prendre des notes ou photographier votre écran.",
      questions: [
        "« Qu’est-ce qui est inclus dans le prix, et qu’est-ce qui ne l’est pas ? »",
        "« Comment vous mesurez les résultats ? »",
        "« Le site m’appartient ? Et si j’arrête l’abonnement ? »",
        "« Qui héberge ? Qui fait les mises à jour ? »",
        "« Vous pouvez me montrer des réalisations dans mon secteur ? »",
      ],
      environment: "Commerce très ordonné : étiquettes alignées, prix affichés partout, horaires précis sur la porte, parfois des certifications ou diplômes encadrés. Caisse moderne, tableaux ou classeurs bien tenus. Souvent dans des métiers de précision : pharmacie, opticien, garage, comptable, caviste.",
      phone: "Répond poliment mais avec distance. Pose des questions précises dès les premières secondes, demande souvent qu’on lui envoie une documentation. Il accepte un rendez-vous s’il comprend exactement ce qu’il va y voir et combien de temps ça dure.",
    },
    wants: [
      "Des faits vérifiables : son classement Google, ses avis, ce que voient ses clients.",
      "Des explications claires et complètes, sans raccourci.",
      "Un devis détaillé, ligne par ligne, et les conditions écrites.",
      "Du temps pour réfléchir et comparer.",
      "Savoir ce qui se passe s’il arrête : propriété du site, durée d’engagement.",
      "Un interlocuteur compétent qui reconnaît quand il ne sait pas.",
    ],
    avoid: [
      "Les formules vagues : « ça va booster votre visibilité ».",
      "Les chiffres inventés ou arrondis à la louche : il vérifiera.",
      "Le presser pour signer le jour même.",
      "Répondre à côté d’une question technique.",
      "L’enthousiasme excessif, qu’il prend pour du baratin.",
      "Promettre un résultat garanti (première page Google, X clients de plus).",
    ],
    close: "Récapitulez point par point ce qui a été vu, puis proposez l’étape suivante logique : l’audit écrit ou un devis détaillé, avec une date de retour précise. Laissez-lui un délai de réflexion et fixez tout de suite le moment où vous en reparlez.",
    phrases: [
      "Je vous montre votre fiche Google telle que vos clients la voient, et vous jugez vous-même.",
      "Tout est détaillé ligne par ligne dans le devis, y compris ce qui se passe si vous arrêtez.",
      "Je préfère ne pas vous donner de chiffre au hasard. Ce que je peux vous montrer, ce sont vos propres données.",
      "L’audit dure 20 minutes, je vous laisse un compte rendu écrit, et vous comparez tranquillement.",
      "Bonne question. Je vérifie et je vous réponds par écrit d’ici jeudi.",
      "On se rappelle vendredi 11 h pour vos questions sur le devis ?",
    ],
  },
  {
    id: "relationnel",
    name: "Le Relationnel",
    tagline: "La confiance d’abord. Il achète à quelqu’un avant d’acheter un service.",
    color: "#15803D",
    recognize: {
      vocabulary: [
        "« Vous êtes d’où, vous ? »",
        "« Ah, vous connaissez untel ? »",
        "« Ici, tout le monde se connaît. »",
        "« Mes clients, ce sont des habitués. »",
        "« Moi, j’ai repris l’affaire de mes parents. »",
        "« Ça marche surtout au bouche-à-oreille. »",
        "« Asseyez-vous, vous voulez un café ? »",
      ],
      pace: "Détendu, bavard. Il digresse, raconte des histoires, parle de sa famille ou du quartier. La conversation peut durer, et c’est bon signe.",
      posture: "Ouvert, souriant, il se rapproche, vous touche parfois le bras. Il salue ses clients par leur prénom pendant que vous êtes là. Il vous regarde dans les yeux et réagit à ce que vous dites.",
      questions: [
        "« Vous êtes d’ici ? »",
        "« Vous travaillez avec qui dans le coin ? »",
        "« Vous êtes combien dans l’agence ? »",
        "« Et c’est vous qui vous occupez de tout, après ? »",
        "« Vous connaissez le restaurant d’à côté ? »",
      ],
      environment: "Commerce chaleureux : photos de famille ou d’anciennes équipes, articles du journal local encadrés, affiche de la fête de la Saint-Louis ou du club de joutes, mots de clients. Ambiance conviviale, habitués accoudés au comptoir.",
      phone: "Décroche chaleureusement, prend le temps de discuter. Il peut vite dire « passez me voir » plutôt que de parler au téléphone. Sa voix se ferme si vous êtes trop commercial ou si vous récitez.",
    },
    wants: [
      "Connaître la personne en face : qui vous êtes, d’où vous venez, pourquoi vous faites ça.",
      "Un partenaire local, joignable, qui passe de temps en temps.",
      "Des références de commerçants qu’il connaît ou dont il a entendu parler.",
      "Qu’on respecte son histoire et l’âme de son commerce.",
      "Être rassuré sur le suivi : « et après, vous serez toujours là ? »",
      "Un échange humain, pas un argumentaire.",
    ],
    avoid: [
      "Aller droit au prix sans avoir pris le temps d’échanger.",
      "Les discours techniques et le jargon.",
      "Couper ses histoires ou regarder votre téléphone pendant qu’il parle.",
      "Critiquer un proche qui s’occupe de sa page Facebook.",
      "Paraître pressé ou tenu par un quota.",
      "Disparaître après la vente.",
    ],
    close: "Appuyez-vous sur la relation créée : proposez de revenir lui montrer l’audit en personne, et fixez le moment ensemble. Rassurez-le sur le suivi (« c’est moi qui m’en occupe, vous avez mon numéro »). Ne forcez jamais : il dira oui quand il vous fera confiance.",
    phrases: [
      "On est à Sète, à côté. Si vous avez un souci, je passe, tout simplement.",
      "Racontez-moi comment vous avez démarré, ça m’intéresse.",
      "Vos habitués vous connaissent. Le but, c’est que les nouveaux vous trouvent aussi.",
      "Je repasse jeudi vous montrer ce que j’ai trouvé, vers 15 h ça vous va ?",
      "C’est moi qui m’en occupe du début à la fin, vous avez mon numéro.",
      "On a fait la carte d’avis pour un commerçant à Frontignan, je peux vous montrer ce que ça donne.",
    ],
  },
  {
    id: "prudent",
    name: "Le Prudent",
    tagline: "Échaudé ou méfiant, il a peur de l’arnaque. Il lui faut des garanties, pas des promesses.",
    color: "#64748B",
    recognize: {
      vocabulary: [
        "« On m’a déjà fait le coup. »",
        "« J’ai déjà eu une agence, j’ai payé pour rien. »",
        "« Je ne signe rien aujourd’hui. »",
        "« C’est quoi le piège ? »",
        "« Il y a un engagement ? »",
        "« Je dois en parler à ma femme / mon associé. »",
        "« Laissez-moi une carte, je verrai. »",
      ],
      pace: "Hésitant, en retrait. Il répond court au début, garde de la distance, et ne s’ouvre qu’une fois rassuré. Il demande du temps et revient souvent sur les mêmes inquiétudes.",
      posture: "Reste derrière le comptoir, recule légèrement, bras croisés, regard qui scrute. Il vérifie votre carte de visite, regarde votre tenue. Il peut appeler un proche avant de répondre.",
      questions: [
        "« Vous existez depuis quand ? »",
        "« Je peux résilier quand je veux ? »",
        "« Qu’est-ce qui me garantit que ça va marcher ? »",
        "« Je paye avant ou après ? »",
        "« Vous avez une adresse, un Siret ? »",
      ],
      environment: "Commerce où l’on sent une mauvaise expérience passée : autocollant « pas de démarchage », vieux site jamais mis à jour avec le nom d’une agence en bas de page, contrat de location de matériel affiché, panneau « paiement comptant uniquement ». Souvent un commerce ancien, prudent sur les dépenses.",
      phone: "Méfiant d’entrée : « Vous avez eu mon numéro comment ? ». Longs silences, réponses brèves, il demande qu’on lui envoie quelque chose par écrit. Il faut ralentir, parler doucement et ne jamais insister.",
    },
    wants: [
      "Des garanties écrites : pas d’engagement caché, résiliation claire.",
      "Commencer petit, sur quelque chose de peu coûteux et vérifiable.",
      "Des preuves que vous êtes réels : adresse, Siret, avis Google de l’agence, réalisations.",
      "Qu’on reconnaisse sa mauvaise expérience sans la minimiser.",
      "Du temps, sans pression.",
      "Voir avant de payer.",
    ],
    avoid: [
      "Toute forme d’urgence ou d’offre « valable aujourd’hui seulement ».",
      "Critiquer l’ancienne agence avec lui : ça vous met dans le même sac.",
      "Promettre des résultats chiffrés.",
      "Pousser un abonnement long dès le premier échange.",
      "Les contrats flous et les petites lignes.",
      "Insister après un « non » clair.",
    ],
    close: "Proposez la plus petite étape sans risque : l’audit gratuit, sans engagement, avec un compte rendu qu’il garde quoi qu’il arrive. Dites clairement ce qu’il ne se passera pas (pas de prélèvement, pas de contrat caché). Laissez-lui le temps et proposez de revenir avec la personne qu’il consulte.",
    phrases: [
      "Je comprends. Qu’est-ce qui s’était mal passé, la dernière fois ?",
      "L’audit est gratuit, sans engagement. Le compte rendu, vous le gardez, même si on ne travaille jamais ensemble.",
      "Pas d’abonnement caché : tout est écrit, et vous pouvez vérifier notre Siret et nos avis avant.",
      "On peut commencer par un petit élément, vous jugez sur pièce, et on voit ensuite.",
      "Prenez le temps d’en parler chez vous. Je peux revenir quand vous serez tous les deux.",
      "On écrit noir sur blanc à qui appartiennent le site et le nom de domaine. C’est la première chose à vérifier chez n’importe quel prestataire.",
    ],
  },
];

export const profileById: Record<DiscProfile, DiscProfileSheet> = {
  fonceur: profiles[0],
  analytique: profiles[1],
  relationnel: profiles[2],
  prudent: profiles[3],
};
